### PR TITLE
Use our own functionallity for scoping CSS

### PR DESCRIPTION
**Pull request by wirdehall**
Okay so I think this will be a huge improvement overall and I will try to go through all the reasons.

**Why did I do this to start with?**
The main reason I started this is that I have been working with scoped css like this in projects for the last two years, just a few weeks ago I finally started a new job where I can work with react again and found this repo to solve that.
The problems I ran into while installing this package in my repo was that:

1. It had 3 moderate severity vulnerabilities. Which all could be derived to old versions of deps `@vue/component-compiler-utils` had.
2. It installed 35 packages when I installed this package, that's almost 12% of all packages in my repo at this point. All deps we have in our repos comes with a cost of maintainging those dependencies and keeping everything up to date and not containing conflicting versions.

**What are the benefits?**

1. By removing `@vue/component-compiler-utils` we removed 16 packages out of 35 this package comes with. Replacing it with css-tree that only comes with 3 deps total. That's a reduction by 13 package, or 37%.
2. Our React projects are not dependent on the whims of the Vue developers. The latest versions of their css processor is already deprecating the ways you recommend in the current version of the docs. Who knows when support will be removed all-togheter and we are left with new syntax that needs to be migrated.
3. My inital (admittedly limited) performance tests shows that this implementation is about 2-4 times faster than `@vue/component-compiler-utils`. Probably a product of using css-tree instead of postcss which is faster and also because we don't need to handle all the cases that Vue carters to. (One example would be inline css in ts files.)
4. This implementation is only 43 lines of code.

**What are the potential issues?**
1. I have removed support for some of the syntax that was available previously such as using `>>>` or `/deep/` and instead now only accepts `::deep` or `::v-deep`.
2. Not sure if this is an issue but, postcss handles sass, less and other such non-standard css. Css-tree does not. In my project at least `@vitejs/plugin-react-swc` is already converting my `scss` files to css before i run this plugin and such I'm never exposed to anything but css. Maybe someone have the order of their plugins ordered differently and that might cause issues.

In general this should be easier to maintain in the longrun and provide us more fine grained control over how this package develops in the future and minimize dependencies on other packages that are unnecessary.

### CODE REVIEW

**Comment by cmseguin** [comment]
First of all, thank you for contributing, I am sorry if I took a little bit to reply to this, times are a little crazy right now!

At first glance this seems like a great idea! I would like to go in that direction, all the points you gave are very valid and makes tons of sense. 

That being said, this is a major change and I want to be careful on how we would implement this. I am slightly concerned by potential issue #2. (SCSS) I currently use it in my flow and I want this to be as plug and play for everyone as possible. I don't want to have special instruction with the plugin on how to use pre-processors.

In the mean time would a quick patch to update the dependencies solve some of your issues?

**Comment by wirdehall** [comment]
Absolutly no worries, you do this on your free time right, I wasn't expecting anthing faster than this :)

I fully understand you regarding this being a major change. I think regardless if we are talking about the potensial issues in point one or two it should probably be a major version update as we are introducing some breaking changes. (how ever small).
That being said I do think point two is less of a problem than you might think.
My vite config looks like this: `plugins: [react(), reactScopedCssPlugin(), tsconfigPaths(), viteCompression()]`
If you remove this lib I'm pretty sure that's what comes with vite when you create a new react+ts project. I havent changed anything in my `vite.config.ts` file since doing my changes in this plugin.
The only caviat now is that if you for some reason had `reactScopedCssPlugin` as the first plugin in the plugin array I think you would have to move it back one step to be after the react plugin.

I can't be sure how the setup would look if you ran this without vite but I'm not sure if that's our target audiance anyways?

Ofcourse an update of deps is always great and I woulden't say no to that but I really think it would be nice for all the reasons mentioned above to merge this. Ofcourse if we need to do some testing of it before hand I don't mind. 

My project isn't in production yet as I'm rewriting two angular code-bases in react so I have a few weeks where I can continue to use my own fork while in local development. But it would be really great if we could get this out with confidence before I'm going to production with my projects.

I don't know what kind of timeline your thinking of regarding testing different setups?

**Comment by wirdehall** [comment]
I found a bug in this implementation when using pseudo-class selectors like :not.
I'm working on a new commit where this issue has been fixed.

**Comment by wirdehall** [comment]
Okay, so I fixed the issues where there were selectors have sub-selectors it would apply the scoping multiple times.
This would happen in the case of for instance the :not() selector. The content inside the parentasis is counted as a sub-select, and would thus be run through the same cycle of applying the scoped data attribute.

I had to more or less re-write it all to get it to work. Now we only apply the data-attribute on top-level selectors and any `deep` pseudo-selectors.
It might be slightly more performant now but it came at the cost of readability and size. (tests show aproximatly 5-10% more performance over the last implementation). 
The implementation grew to 77 lines of code total. The logic unfortunatly became a bit more complex so hopefully we found all bugs now so we don't have to make it more complex.

@cmseguin What's your plan going forward?
Will you do some tests on your own and help work towards a release?

**Comment by wirdehall** [comment]
Okay I have done some more testing.
It appears as though the CSS portion av this plugin does not care about the order of plugins as infact it's vite that converts it from SCSS to CSS before our plugin is run no matter where we put it in the plugin array. 
Unfortunatlly that is not ture for the existing jsx parser as it appears to be dependent on the react plugin to run first. So about my inital worry about "What are the potential issues?" point two in my inital comment. That point is completly moot. Which is great, more reasons to get this merged :D

**Comment by cmseguin** [comment]
Sorry again, late reply!

That's great news, I just updated the deps on main so there are little conflicts now! :) 

I was wondering if you mind if I point this PR to an alpha release of 1.0.0 (1.0.0-alpha.0) that way we can test this release. (I am currently working on a project of my own using this rollup/vite plugin so I will be able to test it with my current usage.)

If you are OK with that I will get that merge very quickly and we will be able to do more testing. 

let me know! :)

**Comment by wirdehall** [comment]
That sounds fantastic!
Alpha release for 1.0.0 is most likely the best way to go here.

Will the alpha release be deployed to npm so we can test the dist version as well?

**Comment by cmseguin** [comment]
Thats the plan :)

**Comment by wirdehall** [comment]
Great!
How does the timeline look like?

**Comment by cmseguin** [comment]
I will try to get that going tonight! I just have to figure out how I wanna
release alpha releases, I would like to setup an action on a branch so that
every new commit automatically publishes a new release!

**Comment by cmseguin** [comment]
Okay so I tried to resolve the conflict as best as I can, the tests seems to fail now but that's ok I will merge this PR to releases/1.0.0-alpha I am working on a workflow that will automatically publish new tags based on the name of the release. If you want to just point your next PR to that branch until it's ready, then I will make an other PR to go to Beta if needs be otherwise straight to main! :)

**Comment by cmseguin** [comment]
Okay so the workflow seems to work 1.0.0-alpha.0 is out and ready to be tested. For the time being can you please do your PR to that branch, when merged it will automatically published a new rc and that way it's easy to test! :)

**Comment by wirdehall** [comment]
Great job!
I already had an ambition to rewrite the test I did by splitting it up and provide the css inline as strings to make the tests more readable and to cover more edge-cases.
I will work on it on Monday and create a PR to the alpha branch.

**Comment by wirdehall** [comment]
I can also see an typo in the updated documentation. It should be `::deep` not `:deep`. Will update that in the same PR.

**Pull request merged**
